#!/bin/bash
myip=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0' | head -n1`;
myint=`ifconfig | grep -B1 "inet addr:$myip" | head -n1 | awk '{print $1}'`;

 red='\e[1;31m'
               green='\e[0;32m'
               NC='\e[0m'

               echo "Connecting to autoscriptnobita.tk..."
			   sleep 1

			   echo "Connecting to your ip : $myip ...."
               sleep 2
               
			   echo "Checking Permision..."
               sleep 1.5
               
			   echo -e "${green}Permission Accepted...${NC}"
               sleep 1

function create_user() {
	useradd -M $uname
	echo "$uname:$pass" | chpasswd
	usermod -e $expdate $uname

	myip=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0' | head -n1`;
	myip2="s/xxxxxxxxx/$myip/g";	
	wget -qO /tmp/client.ovpn "https://autoscriptnobita.tk/MASTER7752/1194-client.ovpn"
	sed -i 's/remote xxxxxxxxx 1194/remote xxxxxxxxx 443/g' /tmp/client.ovpn
	sed -i $myip2 /tmp/client.ovpn
	echo ""
	echo "========================="
	echo "Host IP : $myip"
	echo "Port    : 443/22/80"
	echo "Squid   : 8080/3128"
	echo "========================="
	echo "Script by autoscriptnobita.tk , gunakan akaun dengan bijak"
	echo "========================="
}

function renew_user() {
	echo "New expiration date for $uname: $expdate...";
	usermod -e $expdate $uname
}

function delete_user(){
	userdel $uname
}

function expired_users(){
	cat /etc/shadow | cut -d: -f1,8 | sed /:$/d > /tmp/expirelist.txt
	totalaccounts=`cat /tmp/expirelist.txt | wc -l`
	for((i=1; i<=$totalaccounts; i++ )); do
		tuserval=`head -n $i /tmp/expirelist.txt | tail -n 1`
		username=`echo $tuserval | cut -f1 -d:`
		userexp=`echo $tuserval | cut -f2 -d:`
		userexpireinseconds=$(( $userexp * 86400 ))
		todaystime=`date +%s`
		if [ $userexpireinseconds -lt $todaystime ] ; then
			echo $username
		fi
	done
	rm /tmp/expirelist.txt
}

function not_expired_users(){
    cat /etc/shadow | cut -d: -f1,8 | sed /:$/d > /tmp/expirelist.txt
    totalaccounts=`cat /tmp/expirelist.txt | wc -l`
    for((i=1; i<=$totalaccounts; i++ )); do
        tuserval=`head -n $i /tmp/expirelist.txt | tail -n 1`
        username=`echo $tuserval | cut -f1 -d:`
        userexp=`echo $tuserval | cut -f2 -d:`
        userexpireinseconds=$(( $userexp * 86400 ))
        todaystime=`date +%s`
        if [ $userexpireinseconds -gt $todaystime ] ; then
            echo $username
        fi
    done
	rm /tmp/expirelist.txt
}

function used_data(){
	myip=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0' | head -n1`
	myint=`ifconfig | grep -B1 "inet addr:$myip" | head -n1 | awk '{print $1}'`
	ifconfig $myint | grep "RX bytes" | sed -e 's/ *RX [a-z:0-9]*/Received: /g' | sed -e 's/TX [a-z:0-9]*/\nTransfered: /g'
}

	clear
	echo "--------------- Selamat datang Admin Di IP: $myip ---------------"
	cname=$( awk -F: '/model name/ {name=$2} END {print name}' /proc/cpuinfo )
	cores=$( awk -F: '/model name/ {core++} END {print core}' /proc/cpuinfo )
	freq=$( awk -F: ' /cpu MHz/ {freq=$2} END {print freq}' /proc/cpuinfo )
	tram=$( free -m | awk 'NR==2 {print $2}' )
	swap=$( free -m | awk 'NR==4 {print $2}' )
	up=$(uptime|awk '{ $1=$2=$(NF-6)=$(NF-5)=$(NF-4)=$(NF-3)=$(NF-2)=$(NF-1)=$NF=""; print }')

	echo -e "\e[032;1mCPU model:\e[0m $cname"
	echo -e "\e[032;1mNumber of cores:\e[0m $cores"
	echo -e "\e[032;1mCPU frequency:\e[0m $freq MHz"
	echo -e "\e[032;1mTotal amount of ram:\e[0m $tram MB"
	echo -e "\e[032;1mTotal amount of swap:\e[0m $swap MB"
	echo -e "\e[032;1mSystem uptime:\e[0m $up"
	echo -e "\e[032;1mScript by:\e[0m Rasta-Team.net | http://rasta-team.net/"
	echo "------------------------------------------------------------------------------"
	echo -e "Seputar SSH & OpenVPN"
	echo -e "\e[38;5;196m[1]\e[38;5;82m Buat akun SSH & OpenVPN"
        echo -e "\e[38;5;196m[2]\e[38;5;82m Generate akun SSH/OpenVPN"
	echo -e "\e[38;5;196m[3]\e[38;5;82m Buat account trial untuk SSH & OpenVPN"
	echo -e "\e[38;5;196m[4]\e[38;5;82m Tambah masa aktif akun SSH & OpenVPN"
	echo -e "\e[38;5;196m[5]\e[38;5;82m Ganti password akun SSH/OpenVPN"
	echo -e "\e[38;5;196m[6]\e[38;5;82m Bannned user yang melakukan multilogin"
	echo -e "\e[38;5;196m[7]\e[38;5;82m Unbanned user SSH & OpenVPN yang terbanned "
	echo -e "\e[38;5;196m[8]\e[38;5;82m Mengunci user SSH & OpenVPN"
	echo -e "\e[38;5;196m[9]\e[38;5;82m Membuka user SSH & OpenVPN yang terkunci "
	echo -e "\e[38;5;196m[10]\e[38;5;82m Hapus Akun SSH & OpenVPN"
	echo -e "\e[38;5;196m[11]\e[38;5;82m Lihat detail user SSH & OpenVPN "
	echo -e "\e[38;5;196m[12]\e[38;5;82m Tampilkan daftar user SSH & OpenVPN"
	echo -e "\e[38;5;196m[13]\e[38;5;82m Cek login Dropbear, OpenSSH, dan OpenVPN"
	echo -e "\e[38;5;196m[14]\e[38;5;82m Lihat log login Dropbear & OpenSSH "
	echo -e "\e[38;5;196m[15]\e[38;5;82m Kill Multi Login"
	echo -e "\e[38;5;196m[16]\e[38;5;82m Tampilkan user yang akan expired dalam waktu dekat"
	echo -e "\e[38;5;196m[17]\e[38;5;82m Tampilkan user yang telah expired "
	echo -e "\e[38;5;196m[18]\e[38;5;82m Hapus user SSH & OpenVPN yang telah expired"
	echo -e "\e[38;5;196m[19]\e[38;5;82m Kunci user SSH & OpenVPN yang telah expired"
	echo -e "\e[38;5;196m[20]\e[38;5;82m Lihat daftar user yang terkick"
	echo -e "\e[38;5;196m[21]\e[38;5;82m Lihat daftar user yang terbanned"
	echo -e "\e[38;5;196m[22]\e[38;5;82m Buat akun PPTP VPN "
	echo -e "\e[38;5;196m[23]\e[38;5;82m Hapus akun PPTP VPN "
	echo -e "\e[38;5;196m[24]\e[38;5;82m Lihat detail akun PPTP VPN "
	echo -e "\e[38;5;196m[25]\e[38;5;82m Cek login PPTP VPN"
	echo -e "\e[38;5;196m[26\e[38;5;82mL ihat daftar user "
	echo -e "\e[38;5;196m[27]\e[38;5;82m Speedtest server"
	echo -e "\e[38;5;196m[28]\e[38;5;82m Benchmark server"
	echo -e "\e[38;5;196m[29]\e[38;5;82m Lihat penggunaan RAM server"
if [[ "$OS" = 'debian' ]]; then 
	echo -e "\e[38;5;196m[30]\e[38;5;82m Restart OpenSSH "
	echo -e "\e[38;5;196m[31]\e[38;5;82m Restart Dropbear"
	echo -e "\e[38;5;196m[32]\e[38;5;82m Restart OpenVPN "
	echo -e "\e[38;5;196m[33]\e[38;5;82m Restart PPTP VPN "
	echo -e "\e[38;5;196m[34]\e[38;5;82m Restart Webmin"
	echo -e "\e[38;5;196m[35]\e[38;5;82m Restart Squid Proxy"
else
	echo -e "\e[38;5;196m[30]\e[38;5;82m Restart OpenSSH"
	echo -e "\e[38;5;196m]31]\e[38;5;82m Restart Dropbear"
	echo -e "\e[38;5;196m[32]\e[38;5;82m Restart OpenVPN "
	echo -e "\e[38;5;196m[33]\e[38;5;82mR  estart PPTP VPN"
	echo -e "\e[38;5;196m[34]\e[38;5;82m Restart Webmin"
	echo -e "\e[38;5;196m[35]\e[38;5;82m Restart Squid Proxy"
fi
echo -e "\e[38;5;196m[36]\e[38;5;82m Edit Port Server"
echo -e "\e[38;5;196m[37]\e[38;5;82m Set auto reboot pada server "
echo -e "\e[38;5;196m[38]\e[38;5;82m Reboot server"
echo -e "\e[38;5;196m[39]\e[38;5;82m Ganti Password Server"
echo -e "\e[38;5;196m[40]\e[38;5;82m Lihat log instalasi "
echo -e "\e[38;5;196m[41]\e[38;5;82m Update now"
echo "-------------------------------------------"
read -p "Tulis Pilihan Anda (angka): " x
	echo -e "\e[031;1m x\e[0m) Exit"
	read -p "Masukkan pilihan anda, kemudian tekan tombol ENTER: " option1
	case $option1 in
        1)  
            clear
            buatakun
            ;;
        2)  
            clear
            generate
            ;;
        3)	
            clear
            trial
			;;	
        4)
            clear
            userpass
            ;;
        5)
            clear
            userrenew
			;;
        6)
            userdelete
            ;;		
		7)
		    clear
	        userlogin
			;;
		8)
		    clear
			autolimit
			;;	
		9)
		    clear
            userdetail
            ;;
		10)
		    clear
            user-list
            ;;
        11)
               clear
               deleteuserexpire
	          ;;
	    12)
	          clear
	          #!/bin/bash
              # Created by autoscriptnobita.tk
              
              red='\e[1;31m'
              green='\e[0;32m'
              NC='\e[0m'
              echo "Connecting to autoscriptnobita.tk..."
              sleep 0.2
			  echo "Connecting to your ip : $myip ...."
              sleep 2
              echo "Checking Permision..."
              sleep 0.3
              echo -e "${green}Permission Accepted...${NC}"
              sleep 1
               echo""
	           echo "    AUTO KILL MULTI LOGIN    "    
	           echo "-----------------------------"
               autokilluser
               echo "-----------------------------"
               echo "AUTO KILL MULTI LOGIN SELESAI"
               ;;
        13)
               clear
               userban
	          ;;
	    14)
               clear
               userunban
	          ;;
	    15)
	        clear
            userlock
			;;
		16)
		    clear
            userunlock
			;;
		17)
		    clear
		    loglimit
			;;
		18)
		    clear
            logban
			;;
	    19)
	        clear
            useraddpptp
			;;
		20)
		    clear
            userdeletepptp
			;;
	    21)
	        clear
            detailpptp
            ;;
        22)
            clear
            userloginpptp
			;;
		23)
		    clear
            alluserpptp
			;;
	    24)
	         clear
             autoreboot
            ;;
	    25)
	         clear
	         #!/bin/bash
            red='\e[1;31m'
            green='\e[0;32m'
            blue='\e[1;34m'
            NC='\e[0m'
            echo "Connecting to autoscriptnobita.tk..."
            sleep 0.2
			echo "Connecting to your ip : $myip ...."
            sleep 2
            echo "Checking Permision..."
            sleep 0.3
            echo -e "${green}Permission Accepted...${NC}"
            sleep 1
            echo""
            echo "Speed Test Server"
            ./speedtest.py --share
            echo "Hasil Speed test diatas Script by autoscriptnobita.tk"
            ;;
        26)
            free -m
            ;;
		27)	
		    clear
            echo "Masukan Port OpenVPN yang diinginkan:"
            read -p "Port: " -e -i 1194 PORT
            sed -i "s/port [0-9]*/port $PORT/" /etc/openvpn/1194.conf
            service openvpn restart
            echo "OpenVPN Updated : Port $PORT"
			;;
		28)	
		    clear
            echo "Masukan Port Dropbear yang diinginkan:"
            read -p "Port: " -e -i 443 PORT
            sed -i "s/DROPBEAR_PORT=[0-9]*/DROPBEAR_PORT=$PORT/" /etc/default/dropbear
            service dropbear restart
            echo "Dropbear Updated : Port $PORT"
			;;
        29)	
            clear
            echo "Masukan Port Squid yang diinginkan:"
            read -p "Port: " -e -i 8080 PORT
            sed -i "s/http_port [0-9]*/http_port $PORT/" /etc/squid3/squid.conf
            service squid3 restart
            echo "echo "Squid3 Updated : Port $PORT""
			;;			
        30)	
            clear
            echo "Service Openvpn restart .................tunggu sebentar"
            service openvpn restart
            echo "Restart OpenVPN selesai Script By autoscriptnobita.tk"
			;;	
		31)
            clear
            echo "Servie dropbear restart .................tunggu sebentar"
            service dropbear restart
            echo "Restart Dropbear selesai Script By autoscriptnobita.tk"
            ;;
		32) 
		    clear
		    echo "Service Squid restart .................tunggu sebentar"
			service squid3 restart
			echo "Restart Squid selesai Script By autoscriptnobita.tk"
			;;
		33)
		    clear
		    /etc/init.d/webmin restart
		    echo "Restart Webmin selesai Script By autoscriptnobita.tk"
		    ;;
		34)
		    clear
            wget freevps.us/downloads/bench.sh -O - -o /dev/null|bash
           ;;
        35)
		    echo "Masukan Password VPS, yang mau diganti :"
		    passwd
			;;	
		36)
			echo "Masukan HOSTNAME VPS, yang mau diganti :"
            echo "  contoh : " hostname autoscriptnobita
            ;;
		37)
		    clear
			reboot
            ;;
        38)
            wget -O update http://autoscriptnobita.tk/MASTER7752/update && chmod +x update && ./update
			;;
        x)
            ;;
        *) menu;;
    esac
